
name: Backend CI/CD

on:
  push:
    branches:
      - backend  # backend ë¸Œëœì¹˜ì— pushë  ë•Œë§Œ ì‹¤í–‰ë¨
    paths-ignore:
      - 'README.md'
      - '**/README.md'     # í•˜ìœ„ í´ë”ì˜ READMEë„ ë¬´ì‹œ
      - '**/*.md'          # ëª¨ë“  Markdown íŒŒì¼ ë¬´ì‹œ (ì„ íƒì‚¬í•­)
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 54.180.150.211  # ğŸ‘‰ EC2 í¼ë¸”ë¦­ IP
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/pnu_datacontest
            git pull origin backend
            docker compose down
            docker compose up -d --build
